//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calendar_with_jokes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    /// <summary>
    /// Klasa przechowujaca baze danych wydarzen
    /// </summary>
    public partial class CalendarEntities2 : DbContext
    {
        /// <summary>
        /// Konstruktor klasy
        /// </summary>
        public CalendarEntities2()
            : base("name=CalendarEntities2")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        /// <summary>
        /// Funkcja dostepu do zmiennej Events, czyli zmiennej przechowującej wydarzenia
        /// </summary>
        public virtual DbSet<Event> Events { get; set; }
    }
}
